-- ==========================================
-- RECYCLEBUD DATABASE SCHEMA (PostgreSQL)
-- Run this in Supabase SQL Editor
-- ==========================================

-- 1. ENUMS (Tipe Data Khusus)
CREATE TYPE user_role AS ENUM ('user', 'seller', 'admin');
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'completed', 'cancelled');

-- 2. TABLE: USERS (Menyimpan data profil pengguna)
-- Catatan: Di Supabase, biasanya kita link ini dengan auth.users, tapi untuk simpel kita buat tabel sendiri dulu.
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, -- Di aplikasi nyata, gunakan Supabase Auth
    name TEXT NOT NULL,
    role user_role DEFAULT 'user',
    phone TEXT,
    address TEXT,
    points_balance INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLE: WASTE_TYPES (Master data jenis sampah untuk AI)
CREATE TABLE public.waste_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Contoh: Plastik PET
    description TEXT,
    recycling_guide TEXT, -- Panduan daur ulang
    base_points INTEGER DEFAULT 10, -- Poin dasar jika scan berhasil
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLE: SCAN_HISTORIES (Riwayat scan sampah user)
CREATE TABLE public.scan_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    waste_type_id BIGINT REFERENCES public.waste_types(id),
    image_url TEXT, -- Link gambar hasil upload
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABLE: PRODUCTS (Barang marketplace)
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER DEFAULT 0,
    category TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TABLE: ORDERS (Transaksi pembelian)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status order_status DEFAULT 'pending',
    shipping_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TABLE: ORDER_ITEMS (Detail barang dalam pesanan)
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER NOT NULL,
    price_at_purchase DECIMAL(10, 2) NOT NULL
);

-- 8. TABLE: REWARDS (Katalog hadiah poin)
CREATE TABLE public.rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Contoh: Voucher Belanja 10rb
    points_required INTEGER NOT NULL,
    stock INTEGER DEFAULT 100,
    type TEXT, -- 'voucher', 'donation', dll
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. TABLE: USER_REWARDS (Riwayat penukaran poin)
CREATE TABLE public.user_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    reward_id BIGINT REFERENCES public.rewards(id),
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'active' -- 'active', 'used', 'expired'
);

-- 10. TABLE: LOCATIONS (Peta lokasi bank sampah/mitra)
CREATE TABLE public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    address TEXT,
    type TEXT -- 'bank_sampah' atau 'toko_mitra'
);

-- 11. DATA DUMMY (Opsional: Agar database tidak kosong saat testing)
INSERT INTO public.waste_types (name, description, recycling_guide, base_points) VALUES
('Plastik PET', 'Botol minuman bening', 'Cuci bersih, lepaskan label, dan pipihkan.', 20),
('Kertas Karton', 'Kardus bekas', 'Lipat hingga datar agar hemat tempat.', 15),
('Kaleng Aluminium', 'Kaleng soda', 'Bersihkan sisa minuman, jangan diremukkan jika ingin dikembalikan utuh.', 25);

INSERT INTO public.rewards (name, points_required, type) VALUES
('Voucher Diskon 50%', 500, 'voucher'),
('Donasi 1 Pohon', 1000, 'donation');